# Generated by Django 4.2.7 on 2023-11-07 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmyebook', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='reseñas',
        ),
        migrations.AlterField(
            model_name='libro',
            name='isbn',
            field=models.CharField(max_length=8),
        ),
    ]
