# Generated by Django 4.2.7 on 2023-11-29 18:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appmyebook', '0008_libro_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='genero',
            name='descripcion',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
